version: '3.9'

services:
  db:
    container_name: mysql_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_PASSWORD=123456
      - MYSQL_USER=kompanion
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - mysqlvolume:/var/lib/mysql

volumes:
  mysqlvolume: